"""Apply master fix schema changes

Revision ID: 948aa19df2e6
Revises: 56f30ecfbc46
Create Date: 2026-09-22 20:15:12.988677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948aa19df2e6'
down_revision: Union[str, Sequence[str], None] = '56f30ecfbc46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('token_version', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'deleted_at')
    op.drop_column('admin_users', 'token_version')
    # ### end Alembic commands ###
