"""Add site_settings and visitor tables

Revision ID: b3e2acd9e46a
Revises: 948aa19df2e6
Create Date: 2026-09-23 04:15:50.844006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e2acd9e46a'
down_revision: Union[str, Sequence[str], None] = '948aa19df2e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('next_free_timeline', sa.String(), nullable=True),
    sa.Column('is_hiring', sa.Boolean(), nullable=True),
    sa.Column('accepting_projects', sa.Boolean(), nullable=True),
    sa.Column('hero_title', sa.String(), nullable=True),
    sa.Column('hero_subtitle', sa.String(), nullable=True),
    sa.Column('developer_name', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('site_title', sa.String(), nullable=True),
    sa.Column('site_description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('first_visited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_visited_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitors_ip_address'), 'visitors', ['ip_address'], unique=True)
    op.add_column('projects', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'thumbnail_url')
    op.drop_column('projects', 'image_url')
    op.drop_index(op.f('ix_visitors_ip_address'), table_name='visitors')
    op.drop_table('visitors')
    op.drop_table('site_settings')
    # ### end Alembic commands ###
